# Generated by Django 3.2.5 on 2021-08-10 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('-added_at',)},
        ),
    ]
